name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="tfstate.config"

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Save Plan
      id: save_plan
      run: |
        echo "::set-output name=tfplan::$(cat terraform/tfplan)"
    - name: Archive Plan
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: terraform/tfplan

    - name: Terraform Apply
      if: github.event_name == 'push'
      working-directory: terraform
      run: terraform apply -input=false tfplan

    - name: Terraform Destroy
      if: github.event_name == 'push'
      working-directory: terraform
      run: terraform destroy --auto-approve
