name: Terraform Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip
          unzip terraform_0.12.31_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Validate Terraform configuration
        run: |
          terraform --version
          cd terraform/
          terraform init -backend-config=tfstate.config
          terraform validate

      - name: Plan Terraform deployment
        run: |
          cd terraform/
          terraform init
          terraform plan -out=tfplan
          terraform show -no-color tfplan > tfplan.txt
        continue-on-error: true

      - name: Archive Terraform plan
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Apply Terraform changes
        if: success()
        run: |
          cd terraform/
          terraform apply -input=false tfplan
        env:
          TF_IN_AUTOMATION: "true"
        continue-on-error: true

      - name: Destroy Terraform resources
        if: success()
        run: |
          cd terraform/
          terraform destroy --auto-approve
        continue-on-error: true
